version: "3.9"

services:
  snowflaker1:
    image: ghcr.io/lukeshay/snowflaker:${GIT_SHA:-latest}
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - FLY_MACHINE_ID=RYIq9QlbHun2DS5fAQrrga
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
  snowflaker2:
    image: ghcr.io/lukeshay/snowflaker:${GIT_SHA:-latest}
    build:
      context: .
    ports:
      - 8081:8080
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - FLY_MACHINE_ID=72M7ehE6xCkme27simUHp
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:15.6-alpine3.19
    user: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
